services:
  # Backend API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: addi-backend-api
    ports:
      - "8080:8080"
    environment:
      # Server configuration
      - PORT=8080
      - HOST=0.0.0.0

      # SFTP configuration
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=addiuser
      - SFTP_PASSWORD=addipass
      - SFTP_UPLOAD_DIR=/uploads

      # AWS configuration (uses host credentials)
      - AWS_REGION=us-east-1

    volumes:
      # Mount AWS credentials from host (for local development)
      - ~/.aws:/root/.aws:ro

    depends_on:
      sftp:
        condition: service_started

    networks:
      - addi-network

    restart: unless-stopped

  # SFTP Server
  sftp:
    image: atmoz/sftp:latest
    container_name: addi-sftp-server
    ports:
      - "2222:22"
    volumes:
      # Persistent storage for uploaded files
      - ./sftp/uploads:/home/addiuser/uploads

      # SSH host keys (persistent across restarts)
      - ./sftp/ssh_keys:/etc/ssh/keys

    command: addiuser:addipass:1001:100:uploads

    networks:
      - addi-network

    restart: unless-stopped

  # ngrok tunnel (exposes API to internet)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: addi-ngrok-tunnel
    ports:
      - "4040:4040" # ngrok web UI
    environment:
      # Use your ngrok authtoken (get it from https://dashboard.ngrok.com/get-started/your-authtoken)
      # If not set, will use free tier with random URL
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-2xtf0E1SVfQSpiL9S6iUwnuLznI_uddo2VPakZ8ytW49Y6T7}
    command:
      - "http"
      - "api:8080"
      - "--log=stdout"
    depends_on:
      api:
        condition: service_started
    networks:
      - addi-network
    restart: unless-stopped

networks:
  addi-network:
    driver: bridge
    name: addi-network

volumes:
  sftp-uploads:
    driver: local
